# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c68d32113517c8592f54153e92ad147216727d7f4ca1f03bd72c3af7cf0944ccf86f524fbbd160498b1d347563bd152795c73b1cb4b356d393bc13330dde772

test:
  secret_key_base: 439e06ba2585e6d2a657b5ec8b945027c395cc17d631e2a74b26b9588c8947ac0634e7b1685cfdd9995e1004fe6ece1547dce1de96c45393516914f7ce91f3ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
